theme: jekyll-theme-minimal
name: Matthew Massom
description: Undergraduate Engineering Student
footer-links:
  email: m.massom96@gmail.com
  github: github.com/mmassom96/
  linkedin: linkedin.com/in/matthew-massom-940802137/
