theme: jekyll-theme-minimal
name: Matthew Massom
description: Undergraduate Engineering Student
footer-links:
  email: m.massom96@gmail.com
  github: mmassom96
  linkedin: linkedin.com/in/matthew-massom-940802137/
  twitter: matthewmassom
exclude:
  - index.md
